### ISSUE TITLE
Investigate issue with some domains

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/favicon#11]
1) Users have reported that they are getting issues with the following website:
- buildingradar.com

The favicon seems to be in the source code, it should be found

2) When entering a non-existing domain, we are getting a 500. Investigate why, we might want to rework exception propagation and add more console logs

**Comment by emilienchvt** [comment]
### Diagnosis

The favicon is indeed in the site, available [here](https://buildingradar.com/wp-content/uploads/Favicon.png).

Weirdly, this favicon is not exactly squared:
<img width="169" alt="Screenshot 2023-08-07 at 16 58 46" src="https://github.com/twentyhq/favicon/assets/18351439/e2944a98-9bdd-4ac4-9602-d46d75d3371e">

As a result, it is not used:
https://github.com/twentyhq/favicon/blob/b64eca5866c35bc30630618bf8e3c531b5e2e218/src/favicon/favicon.service.ts#L168

### Proposal

We could:
- Have a specific error management for this case
- Allow "almost-squared" favicons, for example `wdth` and `height` differ by <10% (see linked PR)

**Comment by charlesBochet** [comment]
Good point, let's merge your PR! Also:
- when we don't find an icon we should return a 404 (we are currently returning a 400)
- when we enter a domain that doesn't exist we should return a 404 (we are currently returning a 500)
