### ISSUE TITLE
Progressively refetch favicons

### ISSUE THREAD

**Issue by charlesBochet** [twentyhq/favicon#16]
We would like to have a job to progressively refresh favicons. Each domain should be re-fetched and stored once a week.
We expect to have ~1 million domain stored in the storage. This means that we need to refresh 1 favicon per minute.

Todo once https://github.com/twentyhq/favicon/issues/15 is complete

- use https://docs.nestjs.com/techniques/task-scheduling to declare a cron that would run every 10 minutes and run the command created above

**Comment by gitstart-twenty** [comment]
Hey @charlesBochet ,
This depends on #15 which depends on #13 which is unassigned, so it's kinda blocked.
