### ISSUE TITLE
Missing favicons for some href's

### ISSUE THREAD

**Issue by thilles** [twentyhq/favicon#28]
As discussed in https://discord.com/channels/1130383047699738754/1261068436419776644

Some hrefs found are not a relative link to a `favicon.ico` image, but instead a full url to a static asset, resulting in missing favicons in the twenty-favicon cache. `https://favicon.twenty.com/<companydomain>`.

Another missing favicon is where the href is a relative link to a .svg file.

I believe the href pushed here has to be santized somewhat. 
https://github.com/twentyhq/favicon/blob/81024b6f5da85a7a1b5ec8057c2fa0908953d553/src/favicon/url-fetcher/html.url-fetcher.ts#L42

See example domains nnd.no, unibuss.no and lovenskiold.no

**Comment by charlesBochet** [comment]
Thank you @thilles :)

@gitstart-twenty could you take a look at this one?
